[default]
address = "127.0.0.1"
port = 3030

[development]
address = "127.0.0.1"
port = 3030

[production]
address = "192.168.1.56"
port = 3030

[global.databases]
sqlite_db = { url = "exhibits.db" }

[default.limits]
json = "50 MiB"  # Set the limit to 10 MiB or any other value you need