# .github/workflows/test.yml

name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Rust environment
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          cache: cargo

      # Step 3: Install dependencies if necessary
      - name: Install Backend Dependencies
        run: |
          cd backend
          cargo fetch
          cd ..

      # Step 4: Run Tests
      - name: Run Tests
        run: |
          cd backend
          cargo test --verbose
          cd ..
